
yaml
name: linting-workflow

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  limiting-jobs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Install HTMLHint
        run: npm install --save-dev htmlhint
      - name: Install Stylelint
        run: npm install --save-dev stylelint
      - name: Lint HTML Files
        run: npx htmlhint "**/*.html"
      - name: Lint CSS Files
        run: npx stylelint "**/*.css"
      - name: List Contents of Package.json
        run: cat package.json
